import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Contact from '../components/page-components/contact'
import About from '../components/page-components/about'
import Resume from '../components/page-components/resume'
import Portfolio from '../components/page-components/portfolio'
import { getPortfolioData } from '../utils/api'

export default function Home(props) {
  
  console.log("homepage props", props)

  const aboutPageData = props.aboutPageData
  const resumeData = props.resumeData
  const portfolioData = props.portfolioData

  //  console.log("aboutPageData", props.aboutPageData)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <About aboutPageData={aboutPageData} />
        <Resume resumeData={resumeData} />
        {/* <Skills/> */}
        <Portfolio portfolioData={portfolioData} />
        <Contact />
      </main>

    </div>
  )
}

export const getStaticProps = async () => {



  const data = await getPortfolioData()
 

  console.log("data", data)
  const {
    title,
    body,
    bio,
    intro,
    projects,
     qualifications, 
     referees, 
     interests, 
     strenghts, 
     contactDetails, 
     employment,
      skills,
     
    } = data.data.codingDv.data.attributes

    const aboutPageData = {
      contactDetails: contactDetails,
      title,
      body,
      bio,
    
    }

    const portfolioData = {
      projects: projects,

    }

    const resumeData = {
      education: qualifications,
      work: employment,
      skills: skills,
      
    }


      

  return {

    props: {
      aboutPageData,
      portfolioData,
      resumeData,
    }
  }
}
