import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Contact from '../components/page-components/contact'
import About from '../components/page-components/about'
import Resume from '../components/page-components/resume'
import Portfolio from '../components/page-components/portfolio'
import { getPortfolioData } from '../utils/api'
import Header from '../components/navigation/header/header'

export default function Home(props) {

  console.log("homepage props", props)

  const aboutPageData = props.aboutPageData
  const resumeData = props.resumeData
  const portfolioData = props.portfolioData

  //  console.log("aboutPageData", props.aboutPageData)
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="">




        <About aboutPageData={aboutPageData} />
        <Resume resumeData={resumeData} />
        {/* <Skills/> */}
        <Portfolio portfolioData={portfolioData} />
        <Contact />
        
      </main>

    </div>
  )
}

export const getStaticProps = async () => {



  const data = await getPortfolioData()


  console.log("data", data)
  const {
    title,
    body,
    bio,
    projects,
    qualifications,
    contactDetails,
    employment,
    skills,

  } = data.data.codingDv.data.attributes

  console.log("asshole", projects.map(project => {
    return project.project.data.attributes
  }))

  const aboutPageData = {
    contactDetails: contactDetails,
    title,
    body,
    bio,

  }

  const portfolioData = {
    projects: projects,

  }

  const resumeData = {
    education: qualifications,
    work: employment,
    skills: skills,

  }




  return {

    props: {
      aboutPageData,
      portfolioData,
      resumeData,
    }
  }
}
